---
#
# Test ping for all hosts in inventory
#
- name: Ping all inventory hosts
  hosts: all
  gather_facts: false

  tasks:
    - name: Ping all hosts in inventory from control-node (localhost)
      delegate_to: localhost
      ansible.builtin.command: "ping -c 3 -w 5 {{ ansible_host }}"
      changed_when: false
      register: result
      failed_when:
        - ("100% packet loss" in result.stdout)

    - name: Check ansible/ssh connection
      ansible.builtin.ping:
