---
# check images for missing updated
- name: Check updates
  hosts: all
  tasks:

    - name: Check dnf packages to upgrade
      ansible.builtin.dnf:
        list: updates
      register: dnf_packages
      when: ansible_pkg_mgr == "dnf"

    - name: Check apt packages to upgrade
      ansible.builtin.command: apt list --upgradable
      register: apt_packages
      when: ansible_pkg_mgr == "apt"
      changed_when: false

    - name: Show dnf packages to upgrade
      debug:
        msg: >-
          {%- set output = [] -%}
          {%- for p in dnf_packages.results -%}
          {{ output.append('%-40s' % (p.name ~ '-' ~ p.version) ~ ' | repo: ' ~ p.repo) }}
          {%- endfor -%}
          {{ output }}
      when: ansible_pkg_mgr == "dnf"

    - name: Show apt packages to upgrade
      ansible.builtin.debug:
        msg: >-
          {%- set output = [] -%}
          {%- for p in apt_packages.stdout_lines[1:] -%}
          {{ output.append(p) }}{%- endfor -%}
          {{ output }}
      when: ansible_pkg_mgr == "apt"
